# Generated by Django 3.2.22 on 2023-10-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_arrendamiento_comuna_estacionamiento_reporte_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='direccion',
            new_name='rut',
        ),
    ]
