# Generated by Django 3.2.22 on 2023-10-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20231026_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrendamiento',
            name='hora_fin',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='arrendamiento',
            name='hora_inicio',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
