# Generated by Django 4.2.6 on 2023-10-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20231026_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrendamiento',
            old_name='fecha_inicio',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
