# Generated by Django 3.2.23 on 2023-11-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_fecha_inicio_arrendamiento_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendamiento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('eliminado', 'Eliminado')], default='activo', max_length=20),
        ),
    ]
