# Generated by Django 3.2.23 on 2023-11-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_arrendamiento_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrendamiento',
            old_name='fecha',
            new_name='fecha_inicion',
        ),
    ]
